# ruff: noqa
"""01_initial_schema

Revision ID: 81c53c9ecdc7
Revises: 
Create Date: 2026-07-04 21:09:24.125098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c53c9ecdc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('opening_balance_minor', sa.Integer(), nullable=False),
    sa.Column('current_balance_minor', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_periods',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_budget_period_ym')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_runs',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='dry_run/completed/failed/rolled_back'),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('budget_period_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False, comment='预算金额（分）'),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_period_id'], ['budget_periods.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legacy_archive_records',
    sa.Column('import_run_id', sa.String(length=32), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('legacy_id', sa.String(length=100), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False, comment='脱敏 JSON'),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legacy_id_map',
    sa.Column('import_run_id', sa.String(length=32), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('legacy_id', sa.String(length=100), nullable=False),
    sa.Column('new_table', sa.String(length=100), nullable=False),
    sa.Column('new_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legacy_id_map', schema=None) as batch_op:
        batch_op.create_index('ix_legacy_lookup', ['import_run_id', 'source_table', 'legacy_id'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('account_out_id', sa.String(length=32), nullable=False),
    sa.Column('account_in_id', sa.String(length=32), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False, comment='金额（分）'),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('is_cleared', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True, comment='manual/import/ai'),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_in_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['account_out_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_trans_cat_date', ['category_id', 'transaction_date'], unique=False)
        batch_op.create_index('ix_trans_date_id', ['transaction_date', 'id'], unique=False)
        batch_op.create_index('ix_trans_in_date', ['account_in_id', 'transaction_date'], unique=False)
        batch_op.create_index('ix_trans_out_date', ['account_out_id', 'transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_trans_out_date')
        batch_op.drop_index('ix_trans_in_date')
        batch_op.drop_index('ix_trans_date_id')
        batch_op.drop_index('ix_trans_cat_date')

    op.drop_table('transactions')
    with op.batch_alter_table('legacy_id_map', schema=None) as batch_op:
        batch_op.drop_index('ix_legacy_lookup')

    op.drop_table('legacy_id_map')
    op.drop_table('legacy_archive_records')
    op.drop_table('budget_lines')
    op.drop_table('import_runs')
    op.drop_table('categories')
    op.drop_table('budget_periods')
    op.drop_table('audit_events')
    op.drop_table('app_settings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
